// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vowdhbiwkoaukxmmkmfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvd2RoYml3a29hdWt4bW1rbWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MTQ4MDYsImV4cCI6MjA4ODI5MDgwNn0.kZ76bbHGKNCZRtt_KFZJm8m4n5m3bqqE9iTSgZ1HnjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});